name: Backend CI

on:
  push:
    paths:
      - "backend/**"
      - ".github/workflows/backend-ci.yml"
  pull_request:
    paths:
      - "backend/**"
      - ".github/workflows/backend-ci.yml"

jobs:
  backend-ci:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js 20 with npm cache
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: backend/package-lock.json

      - name: Install dependencies (npm ci)
        run: npm ci

      - name: Lint (if available)
        run: |
          if npm run | grep -q " lint"; then
            npm run lint
          else
            echo "No lint script. Skipping."
          fi

      - name: Run tests (if available)
        run: |
          if npm run | grep -q " test"; then
            npm test
          else
            echo "No test script. Skipping."
          fi