name: Backend CI

on:
  push:
    paths:
      - "backend/**"
      - ".github/workflows/backend-ci.yml"
  pull_request:
    paths:
      - "backend/**"
      - ".github/workflows/backend-ci.yml"

jobs:
  backend-ci:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js 20 with npm cache
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: backend/package-lock.json

      - name: Show npm scripts (debug)
        run: npm run

      - name: Install dependencies (npm ci)
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Run tests
        run: npm test